
db:
  postgres:
    tableNames:
      symbol: "symbol"
      user: "users"
      deal: "deal"
      activeShare: "active_share"
      portfolio: "portfolio"

    drivername: "postgres"
    username: "postgres"
    password: "qwerty"
    dbname: "postgres"
    sslmode: "disable"
    port:

business:
  pricesRefillTime: "3s"